### ISSUE TITLE
Error when logging in on Spigot 1.18.2

### ISSUE THREAD

**Issue by kamoteshake** [TobiasDeBruijn/SkinFixer#34]
**Describe the bug**
Im getting this error on the console when I jump in the server. I can't really pin point why this error is popping. Either my skin is jacked up or something else is going on but could you check the error log if there's something I did wrong? Thanks.

P.S. I removed the plugin and the error is gone and installing it again gives the same error.

```
09.03 03:28:55 [Multicraft] Kamoteshake ran command Message of the Day
09.03 03:28:55 [Server] Server thread/WARN java.lang.NoSuchMethodException: java.lang.Boolean.getProperties()
09.03 03:28:55 [Server] Server thread/WARN at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.bukkitreflectionlib.ReflectionUtil.getMethod(ReflectionUtil.java:157)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.bukkitreflectionlib.ReflectionUtil.invokeMethod(ReflectionUtil.java:242)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.bukkitreflectionlib.ReflectionUtil.invokeMethod(ReflectionUtil.java:225)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.bukkitreflectionlib.ReflectionUtil.invokeMethod(ReflectionUtil.java:173)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.skinfixer.SkinChangeHandler.applySkin1_18(SkinChangeHandler.java:226)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.skinfixer.SkinChangeHandler$3.run(SkinChangeHandler.java:288)
09.03 03:28:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
09.03 03:28:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1289)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1240)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1049)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306)
09.03 03:28:55 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)
09.03 03:28:55 [Server] Server thread/WARN java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutRespawn.<init>(net.minecraft.world.level.dimension.DimensionManager,net.minecraft.resources.ResourceKey,long,net.minecraft.world.level.EnumGamemode,net.minecraft.world.level.EnumGamemode,boolean,boolean,boolean)
09.03 03:28:55 [Server] Server thread/WARN at java.base/java.lang.Class.getConstructor0(Class.java:3585)
09.03 03:28:55 [Server] Server thread/WARN at java.base/java.lang.Class.getConstructor(Class.java:2271)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.bukkitreflectionlib.ReflectionUtil.getConstructor(ReflectionUtil.java:98)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.bukkitreflectionlib.ReflectionUtil.invokeConstructor(ReflectionUtil.java:324)
09.03 03:28:55 [Server] Server thread/WARN at dev.array21.skinfixer.SkinChangeHandler$4.run(SkinChangeHandler.java:428)
09.03 03:28:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
09.03 03:28:55 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1289)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1240)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1049)
09.03 03:28:55 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306)
09.03 03:28:55 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:833)
```

**Screenshots**

**Version information (please complete the following information):**
 - Minecraft version: Spigot 1.18.2
 - SkinFixer version: 1.7.4

**Comment by TobiasDeBruijn** [comment]
Thanks for reporting! Seems the constructor of PacketPlayOutRespawn changed again, will fix ASAP!

**Comment by kamoteshake** [comment]
Thank you so much!

**Comment by kamoteshake** [comment]
I think because of this error, the skin fixer doesn't work on 1.18.2. It would be great if other people can confirm this.

**Comment by TobiasDeBruijn** [comment]
The signature has indeed changed:
Spigot 1.18.1:
```java
public PacketPlayOutRespawn(DimensionManager var0, ResourceKey<World> var1, long var2, EnumGamemode var4, @Nullable EnumGamemode var5, boolean var6, boolean var7, boolean var8) { }
```
Spigot 1.18.2:
```java
public PacketPlayOutRespawn(Holder<DimensionManager> var0, ResourceKey<World> var1, long var2, EnumGamemode var4, @Nullable EnumGamemode var5, boolean var6, boolean var7, boolean var8) { }
```
Besides this some mappings have changed:
- In `net.minecraft.world.entity.player.EntityHuman`: `fp()` becomes `fq()`
- In `net.minecraft.server.level.WorldServer`: `D()` becomes `C()`

With that, SkinFixer works on 1.18.2, and hopefully it will in future versions too without issues.

**Comment by kamoteshake** [comment]
I just tested it, I can confirm that it loaded the skin and there are no more errors. Thank you so much! Great work on fixing it and on the plugin! ❤️
