### ISSUE TITLE
Plugin crashes on MC 1.19

### ISSUE THREAD

**Issue by Beanzilla** [TobiasDeBruijn/SkinFixer#40]
**Describe the bug**
Plugin fails to start up.

**To Reproduce**
1. Get version 1.7.6 of SkinFixer
2. Place it into plugins folder for minecraft server (1.19)
3. Start server and observe logs
4. See kaboom

**Version information (please complete the following information):**
 - Minecraft version: 1.19
 - SkinFixer version: 1.7.6
 - Operating system and OS version: Ubuntu 20.04 LTS
 - Architecture: x86_64

**Additional context**

latest.log
```
[16:06:38] [Server thread/INFO]: [SkinFixer] Enabling SkinFixer v1.7.6
[16:06:38] [Server thread/INFO]: [SkinFixer] Welcome to SkinFixer version 1.7.6 by TheDutchMC!
[16:06:38] [Server thread/WARN]: [SkinFixer] Failed to load libskinfixer. Please open an issue at https://github.com/TheDutchMC/SkinFixer/issues and include your OS, architecture and SkinFixer version. Thanks!
[16:06:38] [Server thread/WARN]: [SkinFixer] java.lang.UnsatisfiedLinkError: /tmp/libskinfixer2781130244838018339/libskinfixer.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libskinfixer2781130244838018339/libskinfixer.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
        at java.base/java.lang.Runtime.load0(Runtime.java:746)
        at java.base/java.lang.System.load(System.java:1857)
        at SkinFixer-1.7.6-RELEASE.jar//dev.array21.skinfixer.storage.LibWrapper.<clinit>(LibWrapper.java:66)
        at SkinFixer-1.7.6-RELEASE.jar//dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:55)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
        at java.base/java.lang.Thread.run(Thread.java:831)

[16:06:38] [Server thread/INFO]: [SkinFixer] libskinfixer loaded.
[16:06:38] [Server thread/ERROR]: Error occurred while enabling SkinFixer v1.7.6 (Is it up to date?)
java.lang.UnsatisfiedLinkError: 'void dev.array21.skinfixer.storage.LibSkinFixer.init(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)'
        at dev.array21.skinfixer.storage.LibSkinFixer.init(Native Method) ~[SkinFixer-1.7.6-RELEASE.jar:?]
        at dev.array21.skinfixer.storage.LibWrapper.init(LibWrapper.java:137) ~[SkinFixer-1.7.6-RELEASE.jar:?]
        at dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:56) ~[SkinFixer-1.7.6-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-60]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[16:06:38] [Server thread/INFO]: [SkinFixer] Disabling SkinFixer v1.7.6
```

**Comment by TobiasDeBruijn** [comment]
This is extremely interesting :thinking: 
It appears your system doesn't have `ld`. How that happened I have no clue though. Is this system managed by yourself or by a hosting provider?

**Comment by TobiasDeBruijn** [comment]
Tried to replicate the issue in a Ubuntu 20.04 LTS server container on x86_64, I'm unable to. Did you by any chance remove the `libc6` package, or removed `ld-linux-86-64.so.2` library yourself?

**Comment by Beanzilla** [comment]
Oops, actually it's not Ubuntu 20.04 LTS, its a version of Alpine. (still linux, just no such package libc6 or ld-linux-86-64.so.2)

> Guess I'm trying to be too fancy with a small server being `openjdk:17-jdk-alpine`.

**Comment by Beanzilla** [comment]
Ok, new error paste:

```
[20:14:25] [Server thread/INFO]: [SkinFixer] Enabling SkinFixer v1.7.6
[20:14:25] [Server thread/INFO]: [SkinFixer] Welcome to SkinFixer version 1.7.6 by TheDutchMC!
[20:14:25] [Server thread/WARN]: [SkinFixer] Failed to load libskinfixer. Please open an issue at https://github.com/TheDutchMC/SkinFixer/issues and include your OS, architecture and SkinFixer version. Thanks!
[20:14:25] [Server thread/WARN]: [SkinFixer] java.lang.UnsatisfiedLinkError: /tmp/libskinfixer10564813986213839749/libskinfixer.so: Error relocating /tmp/libskinfixer10564813986213839749/libskinfixer.so: __register_atfork: symbol not found
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
        at java.base/java.lang.Runtime.load0(Runtime.java:746)
        at java.base/java.lang.System.load(System.java:1857)
        at SkinFixer-1.7.6-RELEASE.jar//dev.array21.skinfixer.storage.LibWrapper.<clinit>(LibWrapper.java:66)
        at SkinFixer-1.7.6-RELEASE.jar//dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:55)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
        at java.base/java.lang.Thread.run(Thread.java:831)

[20:14:25] [Server thread/INFO]: [SkinFixer] libskinfixer loaded.
[20:14:25] [Server thread/ERROR]: Error occurred while enabling SkinFixer v1.7.6 (Is it up to date?)
java.lang.UnsatisfiedLinkError: 'void dev.array21.skinfixer.storage.LibSkinFixer.init(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)'
        at dev.array21.skinfixer.storage.LibSkinFixer.init(Native Method) ~[SkinFixer-1.7.6-RELEASE.jar:?]
        at dev.array21.skinfixer.storage.LibWrapper.init(LibWrapper.java:137) ~[SkinFixer-1.7.6-RELEASE.jar:?]
        at dev.array21.skinfixer.SkinFixer.onEnable(SkinFixer.java:56) ~[SkinFixer-1.7.6-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-60]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-60]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-60]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[20:14:25] [Server thread/INFO]: [SkinFixer] Disabling SkinFixer v1.7.6

```

**Comment by TobiasDeBruijn** [comment]
It's been a while, but glibc /can/ be installed under Alpine. I've done it before, takes some trickery though. Skinfixer does need libc, though.

**Comment by Beanzilla** [comment]
Ah, ok, well for my particular case I guess I will have to break down and use Ubuntu at least till I figure out how to get libc into Alpine.

**Comment by TobiasDeBruijn** [comment]
Good luck!

**Comment by Beanzilla** [comment]
I'm going to close this issue since technically speaking it has nothing really to do with this plugin, just a specific user case.

> Thank you for the help.
