### ISSUE TITLE
Plugin not working on 1.19.4

### ISSUE THREAD

**Issue by michele-grifa** [TobiasDeBruijn/SkinFixer#50]
**Describe the bug**
The plugin loads on 1.19.4, but the skins are not changed at all. 
Also an error is logged in the console, every time a player enter the server or change the skin.

```
[19:48:35 WARN]: java.lang.NoSuchMethodException: java.lang.Boolean.getProperties()
[19:48:35 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.ReflectionUtil.getMethod(ReflectionUtil.java:183)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.ReflectionUtil.invokeMethod(ReflectionUtil.java:268)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.ReflectionUtil.invokeMethod(ReflectionUtil.java:251)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.ReflectionUtil.invokeMethod(ReflectionUtil.java:199)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.abstractions.entity.player.PropertyMap.getInstance(PropertyMap.java:14)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.abstractions.entity.player.GameProfile.getProperties(GameProfile.java:33)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.skinfixer.reflect.PlayerManager.setSkin(PlayerManager.java:94)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.skinfixer.SkinChangeHandler$3.run(SkinChangeHandler.java:118)
[19:48:35 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[19:48:35 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[19:48:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:48:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:48:35 WARN]: [SkinFixer] Unable to reload the Player due to a reflection exception. Is your Minecraft versions supported? Please open a bug report here: https://github.com/TobiasDeBruijn/SkinFixer/issues and attach the following stack trace:
[19:48:35 WARN]: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Boolean (java.lang.Long and java.lang.Boolean are in module java.base of loader 'bootstrap')
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.abstractions.world.CraftWorld.isFlatWorld(CraftWorld.java:52)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.abstractions.packet.PlayerOutRespawnPacket.getPlayerRespawnPacketConstructorArguments(PlayerOutRespawnPacket.java:150)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.bukkitreflectionlib.abstractions.packet.PlayerOutRespawnPacket.getInstance(PlayerOutRespawnPacket.java:46)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.skinfixer.reflect.PlayerManager.reloadPlayer(PlayerManager.java:31)
[19:48:35 WARN]:        at SkinFixer-1.7.8-RELEASE.jar//dev.array21.skinfixer.SkinChangeHandler$4.run(SkinChangeHandler.java:136)
[19:48:35 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[19:48:35 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[19:48:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[19:48:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:48:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
1. Set the skin from a url
2. The skin don't show up

**Expected behavior**
The skins should change with the one i choosed.

**Screenshots**

**Version information (please complete the following information):**
 - Minecraft version: 1.19.4
 - SkinFixer version: 1.7.8
 - Operating system and OS version: Oracle Linux 9
 - Architecture: 

**Additional context**

**Comment by TobiasDeBruijn** [comment]
Thanks for bringing it to my attention.
Forgot I never finished 1.19.4 support.
